---
lowercaseOutputLabelNames: true
lowercaseOutputName: true

rules:

# blacklist JMXONLY metrics
- pattern: "^metrics<name=(.+)><>Count"
  name: "$1_count"
  type: COUNTER

- pattern: "^metrics<name=(.+)><>Value"
  name: "$1"
  type: GAUGE

- pattern: "^metrics<name=(.+)><>(50|75|95|98|99)thPercentile"
  name: "$1"
  type: GAUGE
  labels:
    percentile: "$2"

- pattern: ".*<type=\"(.+)\", scope=\"(.+)\", name=\"(.+)\"><>Count"
  name: "$3_count"
  type: COUNTER
  labels:
    type: "$1"
    scope: "$2"

- pattern: ".*<type=\"(.+)\", name=\"(.+)\"><>Count"
  name: "$2_count"
  type: COUNTER
  labels:
    type: "$1"

- pattern: ".*<type=\"(.+)\", scope=\"(.+)\", name=\"(.+)\"><>Value"
  name: "$3"
  type: GAUGE
  labels:
    type: "$1"
    scope: "$2"

- pattern: ".*<type=\"(.+)\", scope=\"(.+)\", name=\"(.+)\"><>(50|75|95|98|99|999)thPercentile"
  name: "$3"
  type: GAUGE
  labels:
    percentile: "$4"
    type: "$1"
    scope: "$2"

